lib/points_web/router.ex
defmodule PointsWeb.Router do
  use PointsWeb, :router

  import PointsWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PointsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PointsWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PointsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PointsWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", PointsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/auth/:provider", UserOauthController, :request
    get "/auth/:provider/callback", UserOauthController, :callback
  end

  scope "/", PointsWeb do
    pipe_through [:browser, :require_authenticated_user]
    live "/projects", ProjectsLive, :index
    live "/projects/new", ProjectsLive, :new_project
    live "/project/:project_id", ProjectLive, :show
    live "/project/:project_id/edit", ProjectLive, :edit
    live "/project/:project_id/new_story", ProjectLive, :new_story
    live "/story/:story_id", ProjectLive, :edit_story
    live "/sub_project/:sub_project_id", ProjectLive, :show, as: :sub_project
    live "/sub_project/:sub_project_id/new_story", ProjectLive, :new_story, as: :sub_project
  end

  scope "/", PointsWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
  end
end

lib/points_web/views/layout_view.ex
defmodule PointsWeb.LayoutView do
  use PointsWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/points_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/points_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/points_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Points", suffix: " · Points" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <div class="flex flex-col h-screen">
      <header class="py-5 px-5 bg-stone-900 text-white">
        <h1 class="uppercase font-bold text-3xl inline"><%= gettext("Points App") %></h1>
        <div class="float-right pt-1">
          <%= if is_nil(@current_user) do %>
            <%= link gettext("Sign in with Github"), to: Routes.user_oauth_path(@conn, :request, "github"), class: "h-8 px-4 py-2 text-sm text-pink-100 transition-colors duration-150 bg-pink-700 rounded-lg cursor-pointer focus:shadow-outline hover:bg-pink-800 hover:underline" %>
          <% else %>
            <%= link gettext("Sign out"), to: Routes.user_session_path(@conn, :delete), method: :delete, class: "h-8 px-4 py-2 text-sm text-pink-100 transition-colors duration-150 bg-pink-700 rounded-lg cursor-pointer focus:shadow-outline hover:bg-pink-800 hover:underline" %>
          <% end %>
        </div>
      </header>
      <main class="p-5 flex-1">
        <%= @inner_content %>
      </main>
      <footer class="py-5 bg-stone-900 text-center text-white">
        <div class="logo-container">
          <h3 class="logo">
            <a href="https://www.ombulabs.com" target="_blank" title="The Lean Software Boutique">
              <span class="logo-ombu">Ombu</span>Labs
            </a>
          </h3>
          <h2 class="slogan">
            <a href="https://www.ombulabs.com" target="_blank" title="Ombu Labs"> THE LEAN SOFTWARE BOUTIQUE </a>
          </h2>
        </div>
        <div>
          <p><%= gettext("Made with ❤ around the world") %></p>
        </div>
      </footer>
    </div>
  </body>
</html>